### ISSUE TITLE
Biome identifies issues in CI for files that haven't changed/aren't flagged as issues locally.

### ISSUE THREAD

**Issue by tobyurff** [coliving-semkovo/coliving-semkovo#8]
### Describe the bug 📝:

I've created a new branch [experiment/add-reverse-proxy-to-serve-webflow-pages](https://github.com/coliving-semkovo/coliving-semkovo/tree/experiment/add-reverse-proxy-to-serve-webflow-pages) and added an API route, but haven't really touched anything else.

Biome doesn't identify any problems locally.

The Biome step in the CI fails however (https://github.com/coliving-semkovo/coliving-semkovo/actions/runs/8219538349) referring to issues in files that I haven't touched with my commit.

### Steps to reproduce the bug 🔁:

1. Check that last CI build of main ran correctly for step "Biome".
2. Create new branch.
3. Apply a tiny style change to one file that can't possibly cause issues with code quality (e.g. change a "." to a "!" in a text string).
4. Make sure Biome doesn't highlight any issues locally.
5. Push branch.
6. See Biome step in CI fail for the new branch.

**Comment by tobyurff** [comment]
@johnboyes I've got a bit of a curious issue with the CI pipeline in Github Actions where the Biome step marks issues in files that haven't changed at all and that it didn't when we last deployed `main`.

Here's an example for a branch where I only applied a tiny text change in one commit: https://github.com/coliving-semkovo/coliving-semkovo/actions/runs/8219598833

Are you okay to take a look at this when you get a chance?

**Comment by tobyurff** [comment]
To isolate this, it might also be helpful to look at this step being run against `main` two days ago [successfully](https://github.com/coliving-semkovo/coliving-semkovo/actions/runs/8203418913/attempts/1). When I manually re-run it now, it [fails](https://github.com/coliving-semkovo/coliving-semkovo/actions/runs/8203418913) with the same issues.

**Comment by johnboyes** [comment]
Fixed by #10.  As #10 describes, the problem was that we were specifying the Biome GitHub Action (used for CI) to always use the `latest` version of Biome.  This caused the problem above because it automatically picked up the new [1.6.0](https://github.com/biomejs/biome/releases/tag/cli%2Fv1.6.0) version, which has some new checks.

Fix is to no longer specify a Biome version at all in the GitHub Action, meaning that the Action falls back to [automatic version detection](https://github.com/marketplace/actions/setup-biome#automatic-version-detection), using the version in the package.json. This is much better as not only does it fix our build issue but it also guarantees Biome version consistency between our Codespace development environment (i.e the Biome version used by the Codespace Biome VS Code extension) and in CI.
